version: '3.8'

services:
  migrate:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    entrypoint: ["/bin/bash", "-c", "dotnet tool restore && dotnet ef database update"]
    working_dir: /src
    volumes:
      - ./MatthewsGalaxy.ServerDir:/src
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__MatthewsGalaxyConnectionString: "Host=matthewsgalaxy-db;Database=MatthewsGalaxy;Username=postgres;Password=password"
    depends_on:
      - matthewsgalaxy-db

  matthewsgalaxy-db:
    image: "ubuntu/postgres:latest"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "MatthewsGalaxy"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

networks:
  webnet:
    driver: bridge
